- name: variables
  hosts: local
  connection: local
  vars: #PLAY level variable
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Naveen
  tasks:
  - name: print the variables
    ansible.builtin.debug:
       msg : "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"